# Generated by Django 6.0.2 on 2026-02-11 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
