# Generated by Django 5.2.5 on 2026-03-05 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_delete_habits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HabitWeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_days', to='habits.habit')),
            ],
        ),
        migrations.CreateModel(
            name='HabitInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='habits.habit')),
                ('week_days', models.ManyToManyField(blank=True, related_name='infos', to='habits.habitweekday')),
            ],
        ),
        migrations.AddConstraint(
            model_name='habitweekday',
            constraint=models.UniqueConstraint(fields=('habit', 'weekday'), name='unique_habit_weekday'),
        ),
        migrations.AddConstraint(
            model_name='habitinfo',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_date_info'),
        ),
    ]
