# Generated by Django 5.2.5 on 2026-03-08 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_user_habitweekday_habitinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='habitinfo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
    ]
